name: images_keys
description: A simple and easy command-line generation tool generating image assets keys for Dart and Flutter projects.
version: 0.0.3

homepage: https://github.com/DmitryVoronko/images_keys
repository: https://github.com/DmitryVoronko/images_keys
documentation: https://github.com/DmitryVoronko/images_keys
issue_tracker: https://github.com/DmitryVoronko/images_keys/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.15.7
